# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.7.0"
    - run: poetry --version
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint 💅
      run: |
        poetry run black --check --diff .
        poetry run isort --check-only --df .
    - name: Test with pytest
      run: |
        poetry run pytest --cov=wine_aggregator --cov-report html --cov-report xml --cov-report term --junitxml=./build/reports/test-results/report.xml tests/unit
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
      uses: codecov/codecov-action@v3.1.4
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        # Path to coverage file to upload
        # file: # optional
        # Comma-separated list of files to upload
        # files: # optional
        # Directory to search for coverage reports.
        # directory: # optional
        # Specify whether the Codecov output should be verbose
        verbose: false
